[package]
name = "aws_iam_scan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.18.0", features = ["full"]}
aws-sdk-iam = "0.10.1"
"aws-config" = "0.10.1"
